const data = [
  {
    fechaInicio: '',
    nombre: 'Marlene Ordoñez',
    rol: 'Coordinador',
    linea: '2,3',
    correo: 'marlene.ordonez@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'Claudia Muñoz',
    linea: '2,3',
    rol: 'Orientador',
    correo: 'claudiamilenamunozpatino@gmail.com',
  },
  {
    fechaInicio: '',
    nombre: 'María Fernanda Medina',
    linea: '2',
    rol: 'Profesional de apoyo',
    correo: 'fernanda.medina@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'Etna Ximena Velez Guerra',
    linea: '3',
    rol: 'Profesional de apoyo',
    correo: 'etna.velez@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'Harol Manzano',
    rol: 'Coordinador, Profesional de acompañamiento',
    linea: '1',
    correo: 'harold.manzano@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'Lenis Judith Salazar',
    linea: '1',
    rol: 'Orientador',
    correo: 'lenis.salazar@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'María Camila Walteros',
    rol: 'Profesional de apoyo',
    linea: '1',
    correo: 'maria.walteros@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'Constanza López Mazuera',
    rol: 'Profesional de acompañamiento',
    linea: '1',
    correo: 'profe1@correo.com',
  },
  {
    fechaInicio: '',
    nombre: 'Amparo Micolta',
    rol: 'Profesional de acompañamiento',
    linea: '1',
    correo: 'profe2@correo.com',
  },
  {
    fechaInicio: '',
    nombre: 'Wilson Leandro Pardo',
    rol: 'Profesional de acompañamiento',
    linea: '1',
    correo: 'profe3@correo.com',
  },
  {
    fechaInicio: '',
    nombre: 'Uriel Eduardo Torres Castro',
    linea: '1',
    rol: 'Profesional de acompañamiento',
    correo: 'profe4@correo.com',
  },
  {
    fechaInicio: '',
    nombre: 'Andrés azuero',
    rol: 'Coordinador',
    linea: '4,5',
    correo: 'andres.azuero@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'Adriana Reyes',
    rol: 'Orientador',
    linea: '4,5',
    correo: 'adriana.reyes@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'Clara Rosa Echeverry Betancourt',
    rol: 'Profesional de apoyo',
    linea: '4',
    correo: 'clara.echeverry@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'Martín Escobar',
    linea: '5',
    rol: 'Profesional de apoyo',
    correo: 'martin.escobar@correounivalle.edu.co',
  },
  {
    fechaInicio: '',
    nombre: 'ALTA DIRECCIÓN',
    linea: '1,2,3,4,5',
    rol: 'Alta dirección',
    correo: 'profe5@correo.com',
  },
];

export default data;
